// Shared dummy products data
export const dummyProducts = [
  {
    _id: '1',
    name: 'Wireless Bluetooth Headphones',
    description: 'Premium noise-cancelling wireless headphones with 30-hour battery life. Perfect for music lovers and professionals.',
    price: 79.99,
    category: 'Electronics',
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=500',
    ],
    stock_quantity: 50,
    rating: 4.5,
    numReviews: 128,
    brand: 'SoundMax',
    specifications: {
      'Battery Life': '30 hours',
      'Connectivity': 'Bluetooth 5.0',
      'Weight': '250g',
      'Color': 'Black',
    },
  },
  {
    _id: '2',
    name: 'Smart Watch Pro',
    description: 'Feature-rich smartwatch with fitness tracking, heart rate monitor, and smartphone notifications.',
    price: 199.99,
    category: 'Electronics',
    images: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500',
      'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=500',
    ],
    stock_quantity: 30,
    rating: 4.7,
    numReviews: 89,
    brand: 'TechTime',
    specifications: {
      'Display': '1.4 inch AMOLED',
      'Battery': '7 days',
      'Water Resistance': '5 ATM',
      'Compatibility': 'iOS & Android',
    },
  },
  {
    _id: '3',
    name: 'Wireless Earbuds',
    description: 'True wireless earbuds with active noise cancellation and 8-hour battery life. Perfect for workouts and daily use.',
    price: 59.99,
    category: 'Electronics',
    images: [
      'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=500',
      'https://images.unsplash.com/photo-1572569511254-d8f925fe2cbb?w=500',
    ],
    stock_quantity: 75,
    rating: 4.6,
    numReviews: 234,
    brand: 'SoundMax',
    specifications: {
      'Battery Life': '8 hours',
      'Charging Case': '24 hours total',
      'Connectivity': 'Bluetooth 5.2',
      'Noise Cancellation': 'Active',
    },
  },
  {
    _id: '4',
    name: 'Cotton T-Shirt',
    description: 'Comfortable 100% cotton t-shirt. Available in multiple colors. Perfect for everyday wear.',
    price: 19.99,
    category: 'Clothing',
    images: [
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500',
      'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=500',
    ],
    stock_quantity: 200,
    rating: 4.2,
    numReviews: 312,
    brand: 'ComfortWear',
    specifications: {
      'Material': '100% Cotton',
      'Care': 'Machine Wash',
      'Fit': 'Regular',
      'Sizes': 'S, M, L, XL',
    },
  },
  {
    _id: '5',
    name: 'Denim Jeans',
    description: 'Classic fit denim jeans with stretch comfort. Available in multiple washes and sizes.',
    price: 49.99,
    category: 'Clothing',
    images: [
      'https://images.unsplash.com/photo-1542272604-787c3835535d?w=500',
      'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=500',
    ],
    stock_quantity: 120,
    rating: 4.4,
    numReviews: 267,
    brand: 'DenimCo',
    specifications: {
      'Material': '98% Cotton, 2% Elastane',
      'Fit': 'Classic',
      'Wash': 'Multiple options',
      'Sizes': '28-40',
    },
  },
  {
    _id: '6',
    name: 'Hooded Sweatshirt',
    description: 'Warm and comfortable hooded sweatshirt with front pocket. Perfect for casual wear.',
    price: 34.99,
    category: 'Clothing',
    images: [
      'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=500',
      'https://images.unsplash.com/photo-1521223890159-f9d7e0e18743?w=500',
    ],
    stock_quantity: 90,
    rating: 4.5,
    numReviews: 189,
    brand: 'ComfortWear',
    specifications: {
      'Material': '80% Cotton, 20% Polyester',
      'Hood': 'Yes',
      'Pocket': 'Front Kangaroo',
      'Sizes': 'S, M, L, XL, XXL',
    },
  },
  {
    _id: '7',
    name: 'Coffee Maker',
    description: 'Programmable coffee maker with thermal carafe. Makes 12 cups of delicious coffee.',
    price: 69.99,
    category: 'Home & Kitchen',
    images: [
      'https://images.unsplash.com/photo-1517487881594-2787fef5ebf7?w=500',
      'https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=500',
    ],
    stock_quantity: 40,
    rating: 4.5,
    numReviews: 201,
    brand: 'BrewMaster',
    specifications: {
      'Capacity': '12 cups',
      'Programmable': 'Yes',
      'Carafe': 'Thermal',
      'Warranty': '1 year',
    },
  },
  {
    _id: '8',
    name: 'Desk Lamp LED',
    description: 'Adjustable LED desk lamp with touch control and USB charging port. Eye-friendly lighting.',
    price: 34.99,
    category: 'Home & Kitchen',
    images: [
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=500',
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500',
    ],
    stock_quantity: 55,
    rating: 4.4,
    numReviews: 167,
    brand: 'BrightLight',
    specifications: {
      'Brightness': '5 levels',
      'Color Temperature': '3000K-6000K',
      'USB Port': 'Yes',
      'Power': 'LED',
    },
  },
  {
    _id: '9',
    name: 'Air Fryer',
    description: '5.5L capacity air fryer with digital display and multiple cooking presets. Healthier cooking with less oil.',
    price: 79.99,
    category: 'Home & Kitchen',
    images: [
      'https://images.unsplash.com/photo-1608039829570-1c0c0a21c5a0?w=500',
    ],
    stock_quantity: 50,
    rating: 4.7,
    numReviews: 312,
    brand: 'FryMaster',
    specifications: {
      'Capacity': '5.5L',
      'Display': 'Digital',
      'Presets': '8',
      'Power': '1500W',
    },
  },
  {
    _id: '10',
    name: 'Phone Case Protective',
    description: 'Shockproof phone case with screen protector. Compatible with latest smartphones.',
    price: 14.99,
    category: 'Electronics',
    images: [
      'https://images.unsplash.com/photo-1556656793-08538906a9f8?w=500',
      'https://images.unsplash.com/photo-1601972602237-8c79241e468b?w=500',
    ],
    stock_quantity: 150,
    rating: 4.3,
    numReviews: 289,
    brand: 'ProtectPro',
    specifications: {
      'Protection': 'Shockproof',
      'Material': 'TPU & PC',
      'Compatibility': 'Multiple models',
      'Color': 'Clear, Black, Blue',
    },
  },
  {
    _id: '11',
    name: 'Running Shorts',
    description: 'Lightweight running shorts with moisture-wicking fabric and built-in liner.',
    price: 24.99,
    category: 'Clothing',
    images: [
      'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=500',
    ],
    stock_quantity: 150,
    rating: 4.3,
    numReviews: 145,
    brand: 'ActiveWear',
    specifications: {
      'Material': 'Polyester',
      'Moisture Wicking': 'Yes',
      'Liner': 'Built-in',
      'Sizes': 'S, M, L, XL',
    },
  },
  {
    _id: '12',
    name: 'Non-Stick Cookware Set',
    description: '10-piece non-stick cookware set with aluminum base for even heat distribution.',
    price: 89.99,
    category: 'Home & Kitchen',
    images: [
      'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=500',
      'https://images.unsplash.com/photo-1556911220-e15b29be4c69?w=500',
    ],
    stock_quantity: 35,
    rating: 4.6,
    numReviews: 189,
    brand: 'CookPro',
    specifications: {
      'Pieces': '10',
      'Material': 'Non-Stick Coating',
      'Base': 'Aluminum',
      'Dishwasher Safe': 'Yes',
    },
  },
];

// Helper function to get product by ID
export const getProductById = (id: string) => {
  return dummyProducts.find(p => p._id === id) || null;
};

// Helper function to get all products
export const getAllProducts = () => {
  return dummyProducts;
};
